# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f7d7c3e49786fbaf84db647b7bcbcd815760eebdf777249783f026a424e8d359e001c2d61f063ee7db507d8d6f82e3c58de0d9106ba413df03bd05f8e6aec12

test:
  secret_key_base: d7fb7ef4ee123fc1f6d1c8898d0675fbe38b8dceac34f12da11dc3e9b669136dd3cb85e9e8eb12cfbe332c2367df7ef1446b0b5b15af7dc770e54e9ccffe78d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
